keys:
  - &user_noebm age1fjsgndtac7zkappdqtgc8hyaylafhvj234rgf48x2g58278d09hsg0ssnz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_noebm
