#!/usr/bin/env bash

NIXOS_CONFIG=$(dirname -- "${BASH_SOURCE[0]}")
pushd $NIXOS_CONFIG

BRANCH=$(git rev-parse --abbrev-ref HEAD)
sudo nixos-rebuild switch --profile-name ${BRANCH} --flake .

popd


