#!/usr/bin/env bash

set -e

NIXOS_CONFIG=$(dirname -- "${BASH_SOURCE[0]}")
pushd "$NIXOS_CONFIG" || exit

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ $BRANCH == *"/"* ]]; then
  echo "Cannot build nixos configurations with profile names containing '/'."
  echo "Switch or rename branch."
  exit 1
fi

FLAGS=()
if [ "$BRANCH" != "main" ]; then
  FLAGS+=(--profile-name "$BRANCH")
fi

CURRENT=$(readlink /run/current-system)
sudo nixos-rebuild switch "${FLAGS[@]}" --flake .
UPGRADE=$(readlink /run/current-system)

DIFF=$(nvd diff "$CURRENT" "$UPGRADE")

# FIXME: use the proper name (nvd) and check for dependency
echo "The upgrade caused the following changes:"
echo "$DIFF"

echo "Committing changes.."

msg="chore: rebuild triggered"
git commit -am "${msg}

${DIFF}
"


popd || exit


