#!/usr/bin/env bash

NIXOS_CONFIG=$(dirname -- "${BASH_SOURCE[0]}")
pushd "$NIXOS_CONFIG" || exit

git pull

if [ -n "$(git status --porcelain)" ]; then
  echo "Cannot upgrade with uncommited changes present!"
  exit 1
fi

nix flake update

./rebuild

git push

popd || exit


